#src/Basket/BasketBundle/Resources/config/doctrine/Order.orm.yml
Basket\BasketBundle\Entity\Order:
  type: entity
  table: order
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    quantity:
      type: integer
      nullabble: false
      options:
        default : 1
    created:
      type: datetime
      nullable: true
      options:
          default: CURRENT_TIMESTAMP

  oneToOne:
    product:
      targetEntity: Product
      inversedBy: product
      joinColumn:
        name: productId
        referencedColumnName: id

  oneToOne:
      basket:
        targetEntity: Basket
        joinColumn:
          name: basketId
          referencedColumnName: id
