Product_list:
    path:     /
    defaults: { _controller: ProductBundle:Product:list }
    requirements:
             methods:  GET

get_country:
   path:     /getCountry
   defaults: { _controller: ProductBundle:Product:getCountry }
   requirements:
            methods:  GET
