#src/Product/ProductBundle/Resources/config/doctrine/Product.orm.yml
Product\ProductBundle\Entity\Product:
  type: entity
  table: product
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    name:
      type: string
      length: 100
    description:
      type: string
      length: 255
    amount:
      type: float
    count:
       type: integer
       length: 100
    created:
      type: datetime
      nullable: true
      options:
          default: CURRENT_TIMESTAMP